[FEATURE] Use RTE in replacement field
visol/ext-variables pull request #4
Opened 2017-08-16 06:53 UTC by jrenggli

2017-08-16 09:07 UTC, xperseguers commented on Configuration/TCA/tx_variables_marker.php
> +            'defaultExtras' => 'richtext:rte_transform[mode=css]',
official code (in TYPO3 v7) would be

```
'defaultExtras' => 'richtext:rte_transform[mode=ts_css]',
```

2017-08-17 09:09 UTC, jrenggli commented on Configuration/TCA/tx_variables_marker.php
> +            'defaultExtras' => 'richtext:rte_transform[mode=css]',
@xperseguers: Thanks for your response. I just adjusted that... and learnt something new

2017-08-17 09:21 UTC, xperseguers commented
Just for the memo, this effectively allow "some" formatting to be applied to the replacement part, but it does not properly handle links, images, ... since those formatting would require frontend/TS processing on the content coming from the DB.

2017-08-21 08:45 UTC, fanat98 approved these changes

2017-08-24 16:07 UTC, fabarea requested changes

2017-08-24 16:07 UTC, fabarea commented on Configuration/TCA/tx_variables_marker.php
> +            'defaultExtras' => $settings['enableRte']?'richtext:rte_transform[mode=ts_css]':'',
```
$settings['enableRte']
```
May not be an existing index. I know TYPO3 will not complain but nevertheless we should avoid that IMO:

+ PSR-2 formatting needed:

```
$enableRte ? 'richtext:rte_transform[mode=ts_css]' : '',
```

2017-08-24 16:07 UTC, fabarea commented on Configuration/TCA/tx_variables_marker.php
> +$settings = unserialize($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['variables']);
```
$settings = isset($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['variables']) 
    ? unserialize($GLOBALS['TYPO3_CONF_VARS']['EXT']['extConf']['variables'])
    : []
```

2017-08-24 16:07 UTC, fabarea commented on Configuration/TCA/tx_variables_marker.php
> +
```
$enableRte = is_array($settings) && isset($settings['enableRte']) 
   ? (bool)$settings['enableRte']
   : false
```

2017-08-24 17:21 UTC, fabarea approved these changes

2017-08-24 17:23 UTC, jrenggli commented
Thanks for all your inputs...

2017-08-24 17:23 UTC, merged